version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: AAAAKQADAAB1c2VyAHBvc3RncmVzAGRhdGFiYXNlAHBvc3RncmVzAAA=
    postgresResp:
        identfier: PostgresResponse
        length: 13
        payload: UgAAAAwAAAAF7mYwbQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: cAAAAChtZDVmMjY0NmVlZWIyNDQ5OGExYjAyYmRkYzhkMDNmZjBiZQA=
    postgresResp:
        identfier: PostgresResponse
        length: 342
        payload: UgAAAAgAAAAAUwAAABZhcHBsaWNhdGlvbl9uYW1lAABTAAAAGWNsaWVudF9lbmNvZGluZwBVVEY4AFMAAAAXRGF0ZVN0eWxlAElTTywgTURZAFMAAAAZaW50ZWdlcl9kYXRldGltZXMAb24AUwAAABtJbnRlcnZhbFN0eWxlAHBvc3RncmVzAFMAAAAUaXNfc3VwZXJ1c2VyAG9uAFMAAAAZc2VydmVyX2VuY29kaW5nAFVURjgAUwAAADFzZXJ2ZXJfdmVyc2lvbgAxMC41IChEZWJpYW4gMTAuNS0yLnBnZGc5MCsxKQBTAAAAI3Nlc3Npb25fYXV0aG9yaXphdGlvbgBwb3N0Z3JlcwBTAAAAI3N0YW5kYXJkX2NvbmZvcm1pbmdfc3RyaW5ncwBvbgBTAAAAEVRpbWVab25lAFVUQwBLAAAADAAAAB5fMj4MWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 99
        payload: UAAAAEtzdG10Y2FjaGVfMQBTRUxFQ1QgaWQsIG5hbWUsICBwcmljZSBGUk9NIHByb2R1Y3RzIExJTUlUICQxIE9GRlNFVCAkMgAAAEQAAAARU3N0bXRjYWNoZV8xAFMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 101
        payload: MQAAAAR0AAAADgACAAAAFAAAABRUAAAASgADaWQAAABAAgABAAAAFwAE/////wAAbmFtZQAAAEACAAIAAAAZ////////AABwcmljZQAAAEACAAMAAAak//8ACgAGAABaAAAABUk=
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 80
        payload: QgAAADkAc3RtdGNhY2hlXzEAAAIAAQABAAIAAAAIAAAAAAAAAAoAAAAIAAAAAAAAAAAAAwABAAAAAUQAAAAGUABFAAAACQAAAAAAUwAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 501
        payload: MgAAAARUAAAASgADaWQAAABAAgABAAAAFwAE/////wABbmFtZQAAAEACAAIAAAAZ////////AABwcmljZQAAAEACAAMAAAak//8ACgAGAAFEAAAAJwADAAAABAAAAAEAAAAHQnViYmxlcwAAAAoAAQAAAAAAAgB7RAAAACcAAwAAAAQAAAACAAAAB0Z1YmJsZXMAAAAKAAEAAAAAAAIAe0QAAAAnAAMAAAAEAAAAAwAAAAdGdWJibGVzAAAACgABAAAAAAACAHtEAAAAJwADAAAABAAAAAQAAAAHRnViYmxlcwAAAAoAAQAAAAAAAgB7RAAAACcAAwAAAAQAAAAFAAAAB0Z1YmJsZXMAAAAKAAEAAAAAAAIAe0QAAAAnAAMAAAAEAAAABgAAAAdGdWJibGVzAAAACgABAAAAAAACAHtEAAAAJwADAAAABAAAAAcAAAAHRnViYmxlcwAAAAoAAQAAAAAAAgB7RAAAACcAAwAAAAQAAAAIAAAAB0d1YmJsZXMAAAAKAAEAAAAAAAIAe0QAAAAnAAMAAAAEAAAACQAAAAdHdWJibGVzAAAACgABAAAAAAACAHtEAAAAJwADAAAABAAAAAoAAAAHR3ViYmxlcwAAAAoAAQAAAAAAAgB7QwAAAA5TRUxFQ1QgMTAAWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 104
        payload: UAAAAFBzdG10Y2FjaGVfMgBJTlNFUlQgSU5UTyBwcm9kdWN0cyhuYW1lLCBwcmljZSkgVkFMVUVTKCQxLCAkMikgUkVUVVJOSU5HIGlkAAAARAAAABFTc3RtdGNhY2hlXzIAUwAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 54
        payload: MQAAAAR0AAAADgACAAAAGQAABqRUAAAAGwABaWQAAABAAgABAAAAFwAE/////wAAWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 76
        payload: QgAAADUAc3RtdGNhY2hlXzIAAAIAAAABAAIAAAAGQmFuYW5hAAAACgABAAAAAAAAAC0AAQABRAAAAAZQAEUAAAAJAAAAAABTAAAABA==
    postgresResp:
        identfier: PostgresResponse
        length: 70
        payload: MgAAAARUAAAAGwABaWQAAABAAgABAAAAFwAE/////wABRAAAAA4AAQAAAAQAAAAbQwAAAA9JTlNFUlQgMCAxAFoAAAAFSQ==
