version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 13
        payload: UgAAAAwAAAAFMDGxWA==
    postgresResp:
        identfier: ""
        length: 0
        payload: ""
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: cAAAAChtZDU3ZTVlMjNiZTkyNmRlM2Q1ZTA0Nzg2Y2QwMjYzOTM0NQA=
    postgresResp:
        identfier: ""
        length: 0
        payload: ""
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 342
        payload: UgAAAAgAAAAAUwAAABZhcHBsaWNhdGlvbl9uYW1lAABTAAAAGWNsaWVudF9lbmNvZGluZwBVVEY4AFMAAAAXRGF0ZVN0eWxlAElTTywgTURZAFMAAAAZaW50ZWdlcl9kYXRldGltZXMAb24AUwAAABtJbnRlcnZhbFN0eWxlAHBvc3RncmVzAFMAAAAUaXNfc3VwZXJ1c2VyAG9uAFMAAAAZc2VydmVyX2VuY29kaW5nAFVURjgAUwAAADFzZXJ2ZXJfdmVyc2lvbgAxMC41IChEZWJpYW4gMTAuNS0yLnBnZGc5MCsxKQBTAAAAI3Nlc3Npb25fYXV0aG9yaXphdGlvbgBwb3N0Z3JlcwBTAAAAI3N0YW5kYXJkX2NvbmZvcm1pbmdfc3RyaW5ncwBvbgBTAAAAEVRpbWVab25lAFVUQwBLAAAADAAAAcjSE6kIWgAAAAVJ
    postgresResp:
        identfier: ""
        length: 0
        payload: ""
