// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.3
// source: grpc/regression/end.proto

package regression

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EndRequest) Reset() {
	*x = EndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRequest) ProtoMessage() {}

func (x *EndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRequest.ProtoReflect.Descriptor instead.
func (*EndRequest) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{0}
}

func (x *EndRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EndRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EndResponse) Reset() {
	*x = EndResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndResponse) ProtoMessage() {}

func (x *EndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndResponse.ProtoReflect.Descriptor instead.
func (*EndResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{1}
}

func (x *EndResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	App   string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *StartRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	App string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
}

func (x *GetTCRequest) Reset() {
	*x = GetTCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTCRequest) ProtoMessage() {}

func (x *GetTCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTCRequest.ProtoReflect.Descriptor instead.
func (*GetTCRequest) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{4}
}

func (x *GetTCRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTCRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

type GetTCSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App    string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Offset string `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  string `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTCSRequest) Reset() {
	*x = GetTCSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTCSRequest) ProtoMessage() {}

func (x *GetTCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTCSRequest.ProtoReflect.Descriptor instead.
func (*GetTCSRequest) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{5}
}

func (x *GetTCSRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *GetTCSRequest) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *GetTCSRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type GetTCSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tcs []*TestCase `protobuf:"bytes,1,rep,name=tcs,proto3" json:"tcs,omitempty"`
}

func (x *GetTCSResponse) Reset() {
	*x = GetTCSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTCSResponse) ProtoMessage() {}

func (x *GetTCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTCSResponse.ProtoReflect.Descriptor instead.
func (*GetTCSResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{6}
}

func (x *GetTCSResponse) GetTcs() []*TestCase {
	if x != nil {
		return x.Tcs
	}
	return nil
}

type PostTCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TcsId map[string]string `protobuf:"bytes,1,rep,name=tcsId,proto3" json:"tcsId,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PostTCResponse) Reset() {
	*x = PostTCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTCResponse) ProtoMessage() {}

func (x *PostTCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTCResponse.ProtoReflect.Descriptor instead.
func (*PostTCResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{7}
}

func (x *PostTCResponse) GetTcsId() map[string]string {
	if x != nil {
		return x.TcsId
	}
	return nil
}

type DeNoiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeNoiseResponse) Reset() {
	*x = DeNoiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeNoiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeNoiseResponse) ProtoMessage() {}

func (x *DeNoiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeNoiseResponse.ProtoReflect.Descriptor instead.
func (*DeNoiseResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{8}
}

func (x *DeNoiseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pass map[string]bool `protobuf:"bytes,1,rep,name=pass,proto3" json:"pass,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_regression_end_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_regression_end_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_grpc_regression_end_proto_rawDescGZIP(), []int{9}
}

func (x *TestResponse) GetPass() map[string]bool {
	if x != nil {
		return x.Pass
	}
	return nil
}

var File_grpc_regression_end_proto protoreflect.FileDescriptor

var file_grpc_regression_end_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x2f, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65, 0x6e, 0x64,
	0x1a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x34, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36,
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x1f, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x54, 0x43,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x4f, 0x0a, 0x0d, 0x67, 0x65, 0x74,
	0x54, 0x43, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x67, 0x65,
	0x74, 0x54, 0x43, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03,
	0x74, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x52, 0x03, 0x74, 0x63, 0x73, 0x22,
	0x80, 0x01, 0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x74, 0x63, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x63, 0x73, 0x49, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x74, 0x63, 0x73, 0x49, 0x64, 0x1a, 0x38, 0x0a, 0x0a, 0x54, 0x63, 0x73, 0x49,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x2b, 0x0a, 0x0f, 0x64, 0x65, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x78, 0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2f, 0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x65, 0x6e, 0x64, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x50, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x70, 0x61, 0x73, 0x73,
	0x1a, 0x37, 0x0a, 0x09, 0x50, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xd5, 0x02, 0x0a, 0x0a, 0x45, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x12,
	0x0f, 0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x65, 0x6e,
	0x64, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x54, 0x43, 0x12, 0x11, 0x2e, 0x65, 0x6e,
	0x64, 0x2e, 0x67, 0x65, 0x74, 0x54, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x43, 0x53, 0x12, 0x12, 0x2e, 0x65, 0x6e, 0x64, 0x2e,
	0x67, 0x65, 0x74, 0x54, 0x43, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x65, 0x6e, 0x64, 0x2e, 0x67, 0x65, 0x74, 0x54, 0x43, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x44, 0x65, 0x4e, 0x6f, 0x69, 0x73, 0x65,
	0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x64, 0x65, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x65, 0x6e, 0x64, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x6f, 0x2e, 0x6b, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x69,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_regression_end_proto_rawDescOnce sync.Once
	file_grpc_regression_end_proto_rawDescData = file_grpc_regression_end_proto_rawDesc
)

func file_grpc_regression_end_proto_rawDescGZIP() []byte {
	file_grpc_regression_end_proto_rawDescOnce.Do(func() {
		file_grpc_regression_end_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_regression_end_proto_rawDescData)
	})
	return file_grpc_regression_end_proto_rawDescData
}

var file_grpc_regression_end_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_grpc_regression_end_proto_goTypes = []interface{}{
	(*EndRequest)(nil),      // 0: end.endRequest
	(*EndResponse)(nil),     // 1: end.endResponse
	(*StartRequest)(nil),    // 2: end.startRequest
	(*StartResponse)(nil),   // 3: end.startResponse
	(*GetTCRequest)(nil),    // 4: end.getTCRequest
	(*GetTCSRequest)(nil),   // 5: end.getTCSRequest
	(*GetTCSResponse)(nil),  // 6: end.getTCSResponse
	(*PostTCResponse)(nil),  // 7: end.postTCResponse
	(*DeNoiseResponse)(nil), // 8: end.deNoiseResponse
	(*TestResponse)(nil),    // 9: end.testResponse
	nil,                     // 10: end.postTCResponse.TcsIdEntry
	nil,                     // 11: end.testResponse.PassEntry
	(*TestCase)(nil),        // 12: proto.TestCase
	(*TestCaseReq)(nil),     // 13: proto.TestCaseReq
	(*TestReq)(nil),         // 14: proto.TestReq
}
var file_grpc_regression_end_proto_depIdxs = []int32{
	12, // 0: end.getTCSResponse.tcs:type_name -> proto.TestCase
	10, // 1: end.postTCResponse.tcsId:type_name -> end.postTCResponse.TcsIdEntry
	11, // 2: end.testResponse.pass:type_name -> end.testResponse.PassEntry
	0,  // 3: end.EndService.End:input_type -> end.endRequest
	2,  // 4: end.EndService.Start:input_type -> end.startRequest
	4,  // 5: end.EndService.GetTC:input_type -> end.getTCRequest
	5,  // 6: end.EndService.GetTCS:input_type -> end.getTCSRequest
	13, // 7: end.EndService.PostTC:input_type -> proto.TestCaseReq
	14, // 8: end.EndService.DeNoise:input_type -> proto.TestReq
	14, // 9: end.EndService.Test:input_type -> proto.TestReq
	1,  // 10: end.EndService.End:output_type -> end.endResponse
	3,  // 11: end.EndService.Start:output_type -> end.startResponse
	12, // 12: end.EndService.GetTC:output_type -> proto.TestCase
	6,  // 13: end.EndService.GetTCS:output_type -> end.getTCSResponse
	7,  // 14: end.EndService.PostTC:output_type -> end.postTCResponse
	8,  // 15: end.EndService.DeNoise:output_type -> end.deNoiseResponse
	9,  // 16: end.EndService.Test:output_type -> end.testResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_regression_end_proto_init() }
func file_grpc_regression_end_proto_init() {
	if File_grpc_regression_end_proto != nil {
		return
	}
	file_grpc_regression_request_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_regression_end_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTCSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTCSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeNoiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_regression_end_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_regression_end_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_regression_end_proto_goTypes,
		DependencyIndexes: file_grpc_regression_end_proto_depIdxs,
		MessageInfos:      file_grpc_regression_end_proto_msgTypes,
	}.Build()
	File_grpc_regression_end_proto = out.File
	file_grpc_regression_end_proto_rawDesc = nil
	file_grpc_regression_end_proto_goTypes = nil
	file_grpc_regression_end_proto_depIdxs = nil
}
