version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 8
        payload: AAAACATSFi8=
    postgresResp:
        identfier: PostgresResponse
        length: 1
        payload: Tg==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 120
        payload: AAAAeAADAAB1c2VyAGtlcGxveS11c2VyAGRhdGFiYXNlAGtlcGxveS10ZXN0AGNsaWVudF9lbmNvZGluZwBVVEY4AERhdGVTdHlsZQBJU08AVGltZVpvbmUARXRjL1VUQwBleHRyYV9mbG9hdF9kaWdpdHMAMgAA
    postgresResp:
        identfier: PostgresResponse
        length: 13
        payload: UgAAAAwAAAAF+xOCzA==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: cAAAAChtZDUwM2MwZDQwZDllZDkxZDc5ZmZjNjE3YTQ4OWVjMDhkYwA=
    postgresResp:
        identfier: PostgresResponse
        length: 349
        payload: UgAAAAgAAAAAUwAAABZhcHBsaWNhdGlvbl9uYW1lAABTAAAAGWNsaWVudF9lbmNvZGluZwBVVEY4AFMAAAAXRGF0ZVN0eWxlAElTTywgTURZAFMAAAAZaW50ZWdlcl9kYXRldGltZXMAb24AUwAAABtJbnRlcnZhbFN0eWxlAHBvc3RncmVzAFMAAAAUaXNfc3VwZXJ1c2VyAG9uAFMAAAAZc2VydmVyX2VuY29kaW5nAFVURjgAUwAAADFzZXJ2ZXJfdmVyc2lvbgAxMC41IChEZWJpYW4gMTAuNS0yLnBnZGc5MCsxKQBTAAAAJnNlc3Npb25fYXV0aG9yaXphdGlvbgBrZXBsb3ktdXNlcgBTAAAAI3N0YW5kYXJkX2NvbmZvcm1pbmdfc3RyaW5ncwBvbgBTAAAAFVRpbWVab25lAEV0Yy9VVEMASwAAAAwAAAoDSc3OzloAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 63
        payload: UAAAACIAU0VUIGV4dHJhX2Zsb2F0X2RpZ2l0cyA9IDMAAABCAAAADAAAAAAAAAAARQAAAAkAAAAAAVMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 25
        payload: MQAAAAQyAAAABEMAAAAIU0VUAFoAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 84
        payload: UAAAADcAU0VUIGFwcGxpY2F0aW9uX25hbWUgPSAnUG9zdGdyZVNRTCBKREJDIERyaXZlcicAAABCAAAADAAAAAAAAAAARQAAAAkAAAAAAVMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 70
        payload: MQAAAAQyAAAABFMAAAAsYXBwbGljYXRpb25fbmFtZQBQb3N0Z3JlU1FMIEpEQkMgRHJpdmVyAEMAAAAIU0VUAFoAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 67
        payload: UAAAAB8Ac2VsZWN0IGN1cnJlbnRfc2NoZW1hKCkAAABCAAAADAAAAAAAAAAARAAAAAZQAEUAAAAJAAAAAABTAAAABA==
    postgresResp:
        identfier: PostgresResponse
        length: 87
        payload: MQAAAAQyAAAABFQAAAAnAAFjdXJyZW50X3NjaGVtYQAAAAAAAAAAAAATAED/////AABEAAAAEAABAAAABnB1YmxpY0MAAAANU0VMRUNUIDEAWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 67
        payload: UAAAAB8Ac2VsZWN0IGN1cnJlbnRfc2NoZW1hKCkAAABCAAAADAAAAAAAAAAARAAAAAZQAEUAAAAJAAAAAABTAAAABA==
    postgresResp:
        identfier: PostgresResponse
        length: 87
        payload: MQAAAAQyAAAABFQAAAAnAAFjdXJyZW50X3NjaGVtYQAAAAAAAAAAAAATAED/////AABEAAAAEAABAAAABnB1YmxpY0MAAAANU0VMRUNUIDEAWgAAAAVJ
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 5
        payload: WAAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 0
        payload: ""
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 8
        payload: AAAACATSFi8=
    postgresResp:
        identfier: PostgresResponse
        length: 1
        payload: Tg==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 120
        payload: AAAAeAADAAB1c2VyAGtlcGxveS11c2VyAGRhdGFiYXNlAGtlcGxveS10ZXN0AGNsaWVudF9lbmNvZGluZwBVVEY4AERhdGVTdHlsZQBJU08AVGltZVpvbmUARXRjL1VUQwBleHRyYV9mbG9hdF9kaWdpdHMAMgAA
    postgresResp:
        identfier: PostgresResponse
        length: 13
        payload: UgAAAAwAAAAF42OG3A==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 41
        payload: cAAAAChtZDUwMjEyMGM4MzIyNzMxNzJlODM1NTFmNGU5YTgwMGJhMAA=
    postgresResp:
        identfier: PostgresResponse
        length: 349
        payload: UgAAAAgAAAAAUwAAABZhcHBsaWNhdGlvbl9uYW1lAABTAAAAGWNsaWVudF9lbmNvZGluZwBVVEY4AFMAAAAXRGF0ZVN0eWxlAElTTywgTURZAFMAAAAZaW50ZWdlcl9kYXRldGltZXMAb24AUwAAABtJbnRlcnZhbFN0eWxlAHBvc3RncmVzAFMAAAAUaXNfc3VwZXJ1c2VyAG9uAFMAAAAZc2VydmVyX2VuY29kaW5nAFVURjgAUwAAADFzZXJ2ZXJfdmVyc2lvbgAxMC41IChEZWJpYW4gMTAuNS0yLnBnZGc5MCsxKQBTAAAAJnNlc3Npb25fYXV0aG9yaXphdGlvbgBrZXBsb3ktdXNlcgBTAAAAI3N0YW5kYXJkX2NvbmZvcm1pbmdfc3RyaW5ncwBvbgBTAAAAFVRpbWVab25lAEV0Yy9VVEMASwAAAAwAAAoFhTCVsloAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 63
        payload: UAAAACIAU0VUIGV4dHJhX2Zsb2F0X2RpZ2l0cyA9IDMAAABCAAAADAAAAAAAAAAARQAAAAkAAAAAAVMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 25
        payload: MQAAAAQyAAAABEMAAAAIU0VUAFoAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 84
        payload: UAAAADcAU0VUIGFwcGxpY2F0aW9uX25hbWUgPSAnUG9zdGdyZVNRTCBKREJDIERyaXZlcicAAABCAAAADAAAAAAAAAAARQAAAAkAAAAAAVMAAAAE
    postgresResp:
        identfier: PostgresResponse
        length: 70
        payload: MQAAAAQyAAAABFMAAAAsYXBwbGljYXRpb25fbmFtZQBQb3N0Z3JlU1FMIEpEQkMgRHJpdmVyAEMAAAAIU0VUAFoAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 344
        payload: UAAAABcAQkVHSU4gUkVBRCBPTkxZAAAAQgAAAAwAAAAAAAAAAEUAAAAJAAAAAABQAAAA9wBzZWxlY3QgZW1wbG95ZWUwXy5pZCBhcyBpZDFfMF8wXywgZW1wbG95ZWUwXy5lbWFpbCBhcyBlbWFpbDJfMF8wXywgZW1wbG95ZWUwXy5maXJzdF9uYW1lIGFzIGZpcnN0X25hM18wXzBfLCBlbXBsb3llZTBfLmxhc3RfbmFtZSBhcyBsYXN0X25hbTRfMF8wXywgZW1wbG95ZWUwXy50aW1lc3RhbXAgYXMgdGltZXN0YW01XzBfMF8gZnJvbSBlbXBsb3llZXMgZW1wbG95ZWUwXyB3aGVyZSBlbXBsb3llZTBfLmlkPSQxAAABAAAAFEIAAAAaAAAAAQABAAEAAAAIAAAAAAAAAAEAAEQAAAAGUABFAAAACQAAAAAAUwAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 273
        payload: MQAAAAQyAAAABEMAAAAKQkVHSU4AMQAAAAQyAAAABFQAAACiAAVpZDFfMF8wXwAAAEADAAEAAAAUAAj/////AABlbWFpbDJfMF8wXwAAAEADAAIAAAQT//8AAAEDAABmaXJzdF9uYTNfMF8wXwAAAEADAAMAAAQT//8AAAEDAABsYXN0X25hbTRfMF8wXwAAAEADAAQAAAQT//8AAAEDAAB0aW1lc3RhbTVfMF8wXwAAAEADAAUAAAAUAAj/////AABEAAAAOgAFAAAAATEAAAAMbXRAZ21haWwuY29tAAAABE15a2UAAAAFVHlzb24AAAAKMTY5MDg5NjgyOEMAAAANU0VMRUNUIDEAWgAAAAVU
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 49
        payload: UAAAABFTXzEAQ09NTUlUAAAAQgAAAA8AU18xAAAAAAAAAEUAAAAJAAAAAAFTAAAABA==
    postgresResp:
        identfier: PostgresResponse
        length: 28
        payload: MQAAAAQyAAAABEMAAAALQ09NTUlUAFoAAAAFSQ==
---
version: api.keploy.io/v1beta1
kind: Postgres
name: config
spec:
    postgresReq:
        identfier: PostgresReq
        length: 5
        payload: WAAAAAQ=
    postgresResp:
        identfier: PostgresResponse
        length: 0
        payload: ""
